# Generated by Django 4.2.7 on 2023-12-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ei', '0004_details_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('mobile_no', models.BigIntegerField()),
                ('email', models.CharField(max_length=60)),
                ('gender', models.TextField()),
                ('prize', models.IntegerField()),
                ('From', models.CharField(max_length=30)),
                ('To', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('age', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
