# Generated by Django 4.2.7 on 2023-12-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ei', '0005_details1_delete_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='From',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='payment',
            name='To',
            field=models.CharField(max_length=60),
        ),
    ]
