# Generated by Django 5.1.6 on 2025-06-25 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ei', '0011_rename_district_table1_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table1',
            old_name='place',
            new_name='district',
        ),
    ]
