# Generated by Django 5.0 on 2023-12-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ei', '0007_details1_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='details1',
            name='image',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
