# Generated by Django 5.1.6 on 2025-06-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ei', '0010_rename_place_table1_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table1',
            old_name='district',
            new_name='place',
        ),
    ]
