# Generated by Django 5.1.6 on 2025-06-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ei', '0012_rename_place_table1_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='table1',
            name='location',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
